name: Cleanup Old Images
on:
  schedule:
    - cron: "15 0 * * *" # 0015 UTC everyday
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

jobs:
  delete-older-than-90:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@v1.0.13
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: asus-kernel,bazzite-kernel,coreos-stable-kernel,coreos-testing-kernel,fsync-ba-kernel,fsync-kernel,main-kernel,surface-kernel
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7
